### PR TITLE
TS-57 FEATURE - Landing Page

### PR DESCRIPTION
**Pull request by Mark-Ball**
**Mobile**
Screenshot 2024-04-09 at 8 51 10 am
 
**Desktop**
Screenshot 2024-04-09 at 8 51 32 am

### CODE REVIEW

**Comment by Mark-Ball** [comment]
still need the image of the phone in the middle

**Comment by dcarg** [comment]
Screenshot 2024-04-07 at 9 59 26 pm
Screenshot 2024-04-07 at 10 01 18 pm

**Review by dcarg — APPROVED** [review]
👍

**Comment by dcarg** [comment]
I just re centered the top text above the phone image

**Pull request merged**
